### ISSUE TITLE
rename each helper

### ISSUE THREAD

**Issue by jonschlinkert** [philipwalton/ingen#2]
You might consider renaming the [`{{each}}` helper](https://github.com/philipwalton/ingen/blob/master/plugins/post-iterator.js#L17) to something like `{{eachPosts}}` or whatever, since this will override the default each helper included with handlebars, which users may want to use along with this one.

**Comment by philipwalton** [comment]
Yeah, I think you read that line a little too fast :)

``` js
Handlebars.registerHelper('each' + capitalize(type), function(options) { })
```

It creates a helper per post-type. I actually opened [this issue](https://github.com/wycats/handlebars.js/issues/634) with Handlebars in hopes that I could use a "method missing" strategy to create these lazily instead of upfront.

BTW, it looks like I'm working on a similar thing to assemble. I hadn't heard of it until now, but I'll make sure to check it out.

**Comment by jonschlinkert** [comment]
Bah! indeed I did. sorry about that, I was trying to help. 

> it looks like I'm working on a similar thing to assemble.

very cool, we're having a lot of fun with it. and like I mentioned we're about to refactor, so if you decide you want to come over and help out and add some of these great ideas to assemble, that would be awesome. if not, no worries and best of luck!

**Comment by philipwalton** [comment]
Sounds good. I'm mainly doing this for fun and because the features I want for my personal blog have outgrown Jekyll. But once I finish I'll see if it makes sense to merge it into assemble. After all, assemble is a much better name :)

**Comment by jonschlinkert** [comment]
> After all, assemble is a much better name :)

ha! thanks for the compliment. yeah, a friend (@doowb) and I created assemble for similar reasons and it's continued from there. now that you mention your motivations I'm especially interested in hearing your feedback at some point. e.g. what are the features you think are super important to have... anyway, I'll let you get back to work on this!
